export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Body } from "./Body";
export { default as App } from "./App";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Activities } from "./Activities";
export { default as Routines } from "./Routines";
export { default as Createactivities } from "./Createactivities"
