export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Body } from "./Body";
export { default as App } from "./App";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Activities } from "./Activities";
export { default as Routines } from "./Routines";
export { default as Createactivities } from "./Createactivities";
export { default as Createroutine } from "./Createroutine";
export { default as Updateactivities } from "./Updateactivities"
export { default as Updateroutines } from "./Updateroutines"
export { default as Deleteroutine } from "./Deleteroutine"
export { default as UserRoutines } from "./UserRoutines"
